#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

// php run console:connect
$app->add(new \JollyBlueMan\Console\Command\ConnectCommand());
// php run console:greet
$app->add(new \JollyBlueMan\Console\Command\GreetCommand());

// php run console:my-command
$app->add(new \JollyBlueMan\Console\Command\MyCommand());

$app->run();
