<?php

namespace JollyBlueMan\Console\Command;

use JollyBlueMan\Console\Output\Message;
use JollyBlueMan\Console\UtilityBelt\Credentials;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ReportCommand extends Command
{
    protected static string $defaultName = "console:report";
    protected bool $authenticated = false;

    protected function configure()
    {
        $this
            ->setHidden(true)
            ->setDescription("For the issuance of reports.")
            ->setHelp("Sign in for further information.")
        ;

        $this->addArgument('elevation', InputArgument::REQUIRED, '[CLASSIFIED]');

        $this->addOption("data-a", "a",InputArgument::OPTIONAL, "[CLASSIFIED]");
        $this->addOption("data-b", "b",InputArgument::OPTIONAL, "[CLASSIFIED]");
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}